version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ipel-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5r40zfeytv1a"
s3_prefix = "ipel-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
